namespace StorageManager
{
    partial class LoginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panel1 = new System.Windows.Forms.Panel();
            this.ExitBtn = new Bunifu.Framework.UI.BunifuImageButton();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.Login = new System.Windows.Forms.TabPage();
            this.bunifuImageButton1 = new Bunifu.Framework.UI.BunifuImageButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.signInTab = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.loginBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox3 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.passwordLogin = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.emailLogin = new Bunifu.Framework.UI.BunifuMaterialTextbox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.Register = new System.Windows.Forms.TabPage();
            this.errorConfirm = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.errorPassword = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.errorPhone = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.errorEmail = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.errorName = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.confirmReg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.passwordReg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.phoneReg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.emailReg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.nameReg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.loginTab = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.registerBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox4 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ExitBtn)).BeginInit();
            this.bunifuPages1.SuspendLayout();
            this.Login.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuImageButton1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.Register.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorConfirm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorPassword)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorPhone)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorEmail)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox4)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.ExitBtn);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(371, 23);
            this.panel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.panel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.panel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.panel1, "");
            // 
            // ExitBtn
            // 
            this.ExitBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.ExitBtn.Dock = System.Windows.Forms.DockStyle.Right;
            this.ExitBtn.Image = ((System.Drawing.Image)(resources.GetObject("ExitBtn.Image")));
            this.ExitBtn.ImageActive = null;
            this.ExitBtn.Location = new System.Drawing.Point(346, 0);
            this.ExitBtn.Name = "ExitBtn";
            this.ExitBtn.Size = new System.Drawing.Size(25, 23);
            this.ExitBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ExitBtn.TabIndex = 12;
            this.ExitBtn.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.ExitBtn, "");
            this.bunifuToolTip1.SetToolTipIcon(this.ExitBtn, null);
            this.bunifuToolTip1.SetToolTipTitle(this.ExitBtn, "");
            this.ExitBtn.Zoom = 0;
            this.ExitBtn.Click += new System.EventHandler(this.ExitBtn_Click);
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = true;
            this.bunifuPages1.Controls.Add(this.Login);
            this.bunifuPages1.Controls.Add(this.Register);
            this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPages1.Location = new System.Drawing.Point(0, 23);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.Register;
            this.bunifuPages1.PageIndex = 1;
            this.bunifuPages1.PageName = "Register";
            this.bunifuPages1.PageTitle = "Register";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(371, 479);
            this.bunifuPages1.TabIndex = 1;
            this.bunifuToolTip1.SetToolTip(this.bunifuPages1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPages1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPages1, "");
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // Login
            // 
            this.Login.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.Login.Controls.Add(this.bunifuImageButton1);
            this.Login.Controls.Add(this.bunifuButton3);
            this.Login.Controls.Add(this.signInTab);
            this.Login.Controls.Add(this.loginBtn);
            this.Login.Controls.Add(this.bunifuPictureBox3);
            this.Login.Controls.Add(this.passwordLogin);
            this.Login.Controls.Add(this.bunifuPictureBox2);
            this.Login.Controls.Add(this.emailLogin);
            this.Login.Controls.Add(this.bunifuPictureBox1);
            this.Login.Location = new System.Drawing.Point(4, 4);
            this.Login.Name = "Login";
            this.Login.Padding = new System.Windows.Forms.Padding(3);
            this.Login.Size = new System.Drawing.Size(363, 453);
            this.Login.TabIndex = 0;
            this.Login.Text = "Login";
            this.bunifuToolTip1.SetToolTip(this.Login, "");
            this.bunifuToolTip1.SetToolTipIcon(this.Login, null);
            this.bunifuToolTip1.SetToolTipTitle(this.Login, "");
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.BackColor = System.Drawing.Color.White;
            this.bunifuImageButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.Location = new System.Drawing.Point(23, 364);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Size = new System.Drawing.Size(321, 38);
            this.bunifuImageButton1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuImageButton1.TabIndex = 10;
            this.bunifuImageButton1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuImageButton1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuImageButton1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuImageButton1, "");
            this.bunifuImageButton1.Zoom = 0;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Forgot your password ?";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges1;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.IdleBorderRadius = 3;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(108, 277);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.onHoverState.BorderRadius = 3;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.OnIdleState.BorderRadius = 3;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 3;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(163, 23);
            this.bunifuButton3.TabIndex = 9;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuButton3, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton3, "");
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // signInTab
            // 
            this.signInTab.AllowToggling = false;
            this.signInTab.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.signInTab.AnimationSpeed = 200;
            this.signInTab.AutoGenerateColors = false;
            this.signInTab.BackColor = System.Drawing.Color.Transparent;
            this.signInTab.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("signInTab.BackgroundImage")));
            this.signInTab.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signInTab.ButtonText = "Register";
            this.signInTab.ButtonTextMarginLeft = 0;
            this.signInTab.ColorContrastOnClick = 45;
            this.signInTab.ColorContrastOnHover = 45;
            this.signInTab.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.signInTab.CustomizableEdges = borderEdges2;
            this.signInTab.DialogResult = System.Windows.Forms.DialogResult.None;
            this.signInTab.DisabledBorderColor = System.Drawing.Color.Empty;
            this.signInTab.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.signInTab.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.signInTab.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.signInTab.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.signInTab.ForeColor = System.Drawing.Color.White;
            this.signInTab.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.signInTab.IconMarginLeft = 11;
            this.signInTab.IconPadding = 10;
            this.signInTab.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.signInTab.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.IdleBorderRadius = 3;
            this.signInTab.IdleBorderThickness = 1;
            this.signInTab.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.IdleIconLeftImage = null;
            this.signInTab.IdleIconRightImage = null;
            this.signInTab.IndicateFocus = false;
            this.signInTab.Location = new System.Drawing.Point(145, 411);
            this.signInTab.Name = "signInTab";
            this.signInTab.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.onHoverState.BorderRadius = 3;
            this.signInTab.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signInTab.onHoverState.BorderThickness = 1;
            this.signInTab.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.signInTab.onHoverState.IconLeftImage = null;
            this.signInTab.onHoverState.IconRightImage = null;
            this.signInTab.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.OnIdleState.BorderRadius = 3;
            this.signInTab.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signInTab.OnIdleState.BorderThickness = 1;
            this.signInTab.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.signInTab.OnIdleState.IconLeftImage = null;
            this.signInTab.OnIdleState.IconRightImage = null;
            this.signInTab.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.OnPressedState.BorderRadius = 3;
            this.signInTab.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signInTab.OnPressedState.BorderThickness = 1;
            this.signInTab.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.signInTab.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.signInTab.OnPressedState.IconLeftImage = null;
            this.signInTab.OnPressedState.IconRightImage = null;
            this.signInTab.Size = new System.Drawing.Size(73, 23);
            this.signInTab.TabIndex = 8;
            this.signInTab.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.signInTab.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.signInTab, "");
            this.bunifuToolTip1.SetToolTipIcon(this.signInTab, null);
            this.bunifuToolTip1.SetToolTipTitle(this.signInTab, "");
            this.signInTab.UseDefaultRadiusAndThickness = true;
            this.signInTab.Click += new System.EventHandler(this.signUpTab_Click);
            // 
            // loginBtn
            // 
            this.loginBtn.AllowToggling = false;
            this.loginBtn.AnimationSpeed = 200;
            this.loginBtn.AutoGenerateColors = false;
            this.loginBtn.BackColor = System.Drawing.Color.Transparent;
            this.loginBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginBtn.BackgroundImage")));
            this.loginBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginBtn.ButtonText = "Login";
            this.loginBtn.ButtonTextMarginLeft = 0;
            this.loginBtn.ColorContrastOnClick = 45;
            this.loginBtn.ColorContrastOnHover = 45;
            this.loginBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.loginBtn.CustomizableEdges = borderEdges3;
            this.loginBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.loginBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.loginBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.loginBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.loginBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.loginBtn.ForeColor = System.Drawing.Color.White;
            this.loginBtn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.loginBtn.IconMarginLeft = 11;
            this.loginBtn.IconPadding = 10;
            this.loginBtn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.loginBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginBtn.IdleBorderRadius = 3;
            this.loginBtn.IdleBorderThickness = 1;
            this.loginBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginBtn.IdleIconLeftImage = null;
            this.loginBtn.IdleIconRightImage = null;
            this.loginBtn.IndicateFocus = false;
            this.loginBtn.Location = new System.Drawing.Point(23, 320);
            this.loginBtn.Name = "loginBtn";
            this.loginBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginBtn.onHoverState.BorderRadius = 3;
            this.loginBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginBtn.onHoverState.BorderThickness = 1;
            this.loginBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.loginBtn.onHoverState.IconLeftImage = null;
            this.loginBtn.onHoverState.IconRightImage = null;
            this.loginBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginBtn.OnIdleState.BorderRadius = 3;
            this.loginBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginBtn.OnIdleState.BorderThickness = 1;
            this.loginBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.loginBtn.OnIdleState.IconLeftImage = null;
            this.loginBtn.OnIdleState.IconRightImage = null;
            this.loginBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.loginBtn.OnPressedState.BorderRadius = 3;
            this.loginBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginBtn.OnPressedState.BorderThickness = 1;
            this.loginBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.loginBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.loginBtn.OnPressedState.IconLeftImage = null;
            this.loginBtn.OnPressedState.IconRightImage = null;
            this.loginBtn.Size = new System.Drawing.Size(321, 38);
            this.loginBtn.TabIndex = 6;
            this.loginBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.loginBtn.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.loginBtn, "");
            this.bunifuToolTip1.SetToolTipIcon(this.loginBtn, null);
            this.bunifuToolTip1.SetToolTipTitle(this.loginBtn, "");
            this.loginBtn.UseDefaultRadiusAndThickness = true;
            this.loginBtn.Click += new System.EventHandler(this.loginBtn_Click);
            // 
            // bunifuPictureBox3
            // 
            this.bunifuPictureBox3.AllowFocused = false;
            this.bunifuPictureBox3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox3.BorderRadius = 0;
            this.bunifuPictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox3.Image")));
            this.bunifuPictureBox3.IsCircle = false;
            this.bunifuPictureBox3.Location = new System.Drawing.Point(20, 227);
            this.bunifuPictureBox3.Name = "bunifuPictureBox3";
            this.bunifuPictureBox3.Size = new System.Drawing.Size(36, 36);
            this.bunifuPictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox3.TabIndex = 5;
            this.bunifuPictureBox3.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox3, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox3, "");
            this.bunifuPictureBox3.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // passwordLogin
            // 
            this.passwordLogin.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.passwordLogin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordLogin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordLogin.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordLogin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordLogin.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.passwordLogin.ForeColor = System.Drawing.Color.White;
            this.passwordLogin.HintForeColor = System.Drawing.Color.White;
            this.passwordLogin.HintText = "Password";
            this.passwordLogin.isPassword = true;
            this.passwordLogin.LineFocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.passwordLogin.LineIdleColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.passwordLogin.LineMouseHoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.passwordLogin.LineThickness = 2;
            this.passwordLogin.Location = new System.Drawing.Point(64, 223);
            this.passwordLogin.Margin = new System.Windows.Forms.Padding(5);
            this.passwordLogin.MaxLength = 32767;
            this.passwordLogin.Name = "passwordLogin";
            this.passwordLogin.Size = new System.Drawing.Size(277, 40);
            this.passwordLogin.TabIndex = 4;
            this.passwordLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuToolTip1.SetToolTip(this.passwordLogin, "");
            this.bunifuToolTip1.SetToolTipIcon(this.passwordLogin, null);
            this.bunifuToolTip1.SetToolTipTitle(this.passwordLogin, "");
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = false;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(21, 178);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(36, 36);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 3;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox2, "");
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // emailLogin
            // 
            this.emailLogin.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.emailLogin.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailLogin.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailLogin.characterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailLogin.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailLogin.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailLogin.ForeColor = System.Drawing.Color.White;
            this.emailLogin.HintForeColor = System.Drawing.Color.White;
            this.emailLogin.HintText = "Email";
            this.emailLogin.isPassword = false;
            this.emailLogin.LineFocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.emailLogin.LineIdleColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.emailLogin.LineMouseHoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.emailLogin.LineThickness = 2;
            this.emailLogin.Location = new System.Drawing.Point(65, 174);
            this.emailLogin.Margin = new System.Windows.Forms.Padding(5);
            this.emailLogin.MaxLength = 32767;
            this.emailLogin.Name = "emailLogin";
            this.emailLogin.Size = new System.Drawing.Size(277, 40);
            this.emailLogin.TabIndex = 1;
            this.emailLogin.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuToolTip1.SetToolTip(this.emailLogin, "");
            this.bunifuToolTip1.SetToolTipIcon(this.emailLogin, null);
            this.bunifuToolTip1.SetToolTipTitle(this.emailLogin, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(95, -18);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(173, 173);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // Register
            // 
            this.Register.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.Register.Controls.Add(this.errorConfirm);
            this.Register.Controls.Add(this.errorPassword);
            this.Register.Controls.Add(this.errorPhone);
            this.Register.Controls.Add(this.errorEmail);
            this.Register.Controls.Add(this.errorName);
            this.Register.Controls.Add(this.confirmReg);
            this.Register.Controls.Add(this.passwordReg);
            this.Register.Controls.Add(this.phoneReg);
            this.Register.Controls.Add(this.emailReg);
            this.Register.Controls.Add(this.nameReg);
            this.Register.Controls.Add(this.loginTab);
            this.Register.Controls.Add(this.registerBtn);
            this.Register.Controls.Add(this.bunifuLabel1);
            this.Register.Controls.Add(this.bunifuPictureBox4);
            this.Register.Location = new System.Drawing.Point(4, 4);
            this.Register.Name = "Register";
            this.Register.Padding = new System.Windows.Forms.Padding(3);
            this.Register.Size = new System.Drawing.Size(363, 453);
            this.Register.TabIndex = 1;
            this.Register.Text = "Register";
            this.bunifuToolTip1.SetToolTip(this.Register, "");
            this.bunifuToolTip1.SetToolTipIcon(this.Register, null);
            this.bunifuToolTip1.SetToolTipTitle(this.Register, "");
            // 
            // errorConfirm
            // 
            this.errorConfirm.AllowFocused = false;
            this.errorConfirm.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.errorConfirm.BorderRadius = 0;
            this.errorConfirm.Image = ((System.Drawing.Image)(resources.GetObject("errorConfirm.Image")));
            this.errorConfirm.IsCircle = false;
            this.errorConfirm.Location = new System.Drawing.Point(297, 320);
            this.errorConfirm.Name = "errorConfirm";
            this.errorConfirm.Size = new System.Drawing.Size(17, 17);
            this.errorConfirm.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.errorConfirm.TabIndex = 22;
            this.errorConfirm.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.errorConfirm, "");
            this.bunifuToolTip1.SetToolTipIcon(this.errorConfirm, null);
            this.bunifuToolTip1.SetToolTipTitle(this.errorConfirm, "");
            this.errorConfirm.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.errorConfirm.Visible = false;
            // 
            // errorPassword
            // 
            this.errorPassword.AllowFocused = false;
            this.errorPassword.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.errorPassword.BorderRadius = 0;
            this.errorPassword.Image = ((System.Drawing.Image)(resources.GetObject("errorPassword.Image")));
            this.errorPassword.IsCircle = false;
            this.errorPassword.Location = new System.Drawing.Point(297, 263);
            this.errorPassword.Name = "errorPassword";
            this.errorPassword.Size = new System.Drawing.Size(17, 17);
            this.errorPassword.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.errorPassword.TabIndex = 21;
            this.errorPassword.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.errorPassword, "");
            this.bunifuToolTip1.SetToolTipIcon(this.errorPassword, null);
            this.bunifuToolTip1.SetToolTipTitle(this.errorPassword, "");
            this.errorPassword.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.errorPassword.Visible = false;
            // 
            // errorPhone
            // 
            this.errorPhone.AllowFocused = false;
            this.errorPhone.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.errorPhone.BorderRadius = 0;
            this.errorPhone.Image = ((System.Drawing.Image)(resources.GetObject("errorPhone.Image")));
            this.errorPhone.IsCircle = false;
            this.errorPhone.Location = new System.Drawing.Point(297, 206);
            this.errorPhone.Name = "errorPhone";
            this.errorPhone.Size = new System.Drawing.Size(17, 17);
            this.errorPhone.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.errorPhone.TabIndex = 20;
            this.errorPhone.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.errorPhone, "");
            this.bunifuToolTip1.SetToolTipIcon(this.errorPhone, null);
            this.bunifuToolTip1.SetToolTipTitle(this.errorPhone, "");
            this.errorPhone.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.errorPhone.Visible = false;
            // 
            // errorEmail
            // 
            this.errorEmail.AllowFocused = false;
            this.errorEmail.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.errorEmail.BorderRadius = 0;
            this.errorEmail.Image = ((System.Drawing.Image)(resources.GetObject("errorEmail.Image")));
            this.errorEmail.IsCircle = false;
            this.errorEmail.Location = new System.Drawing.Point(297, 149);
            this.errorEmail.Name = "errorEmail";
            this.errorEmail.Size = new System.Drawing.Size(17, 17);
            this.errorEmail.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.errorEmail.TabIndex = 19;
            this.errorEmail.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.errorEmail, "");
            this.bunifuToolTip1.SetToolTipIcon(this.errorEmail, null);
            this.bunifuToolTip1.SetToolTipTitle(this.errorEmail, "");
            this.errorEmail.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.errorEmail.Visible = false;
            // 
            // errorName
            // 
            this.errorName.AllowFocused = false;
            this.errorName.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.errorName.BorderRadius = 0;
            this.errorName.Image = ((System.Drawing.Image)(resources.GetObject("errorName.Image")));
            this.errorName.IsCircle = false;
            this.errorName.Location = new System.Drawing.Point(297, 92);
            this.errorName.Name = "errorName";
            this.errorName.Size = new System.Drawing.Size(17, 17);
            this.errorName.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.errorName.TabIndex = 18;
            this.errorName.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.errorName, "");
            this.bunifuToolTip1.SetToolTipIcon(this.errorName, null);
            this.bunifuToolTip1.SetToolTipTitle(this.errorName, "");
            this.errorName.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.errorName.Visible = false;
            // 
            // confirmReg
            // 
            this.confirmReg.AcceptsReturn = false;
            this.confirmReg.AcceptsTab = false;
            this.confirmReg.AnimationSpeed = 200;
            this.confirmReg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.confirmReg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.confirmReg.BackColor = System.Drawing.Color.Transparent;
            this.confirmReg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("confirmReg.BackgroundImage")));
            this.confirmReg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.confirmReg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.confirmReg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.confirmReg.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.confirmReg.BorderRadius = 1;
            this.confirmReg.BorderThickness = 3;
            this.confirmReg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.confirmReg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.confirmReg.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.confirmReg.DefaultText = "";
            this.confirmReg.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.confirmReg.ForeColor = System.Drawing.Color.White;
            this.confirmReg.HideSelection = true;
            this.confirmReg.IconLeft = null;
            this.confirmReg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.confirmReg.IconPadding = 10;
            this.confirmReg.IconRight = null;
            this.confirmReg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.confirmReg.Lines = new string[0];
            this.confirmReg.Location = new System.Drawing.Point(38, 311);
            this.confirmReg.MaxLength = 32767;
            this.confirmReg.MinimumSize = new System.Drawing.Size(1, 1);
            this.confirmReg.Modified = false;
            this.confirmReg.Multiline = false;
            this.confirmReg.Name = "confirmReg";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirmReg.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.confirmReg.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirmReg.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.confirmReg.OnIdleState = stateProperties4;
            this.confirmReg.PasswordChar = '*';
            this.confirmReg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.confirmReg.PlaceholderText = "Password";
            this.confirmReg.ReadOnly = false;
            this.confirmReg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.confirmReg.SelectedText = "";
            this.confirmReg.SelectionLength = 0;
            this.confirmReg.SelectionStart = 0;
            this.confirmReg.ShortcutsEnabled = true;
            this.confirmReg.Size = new System.Drawing.Size(287, 35);
            this.confirmReg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.confirmReg.TabIndex = 17;
            this.confirmReg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.confirmReg.TextMarginBottom = 0;
            this.confirmReg.TextMarginLeft = 5;
            this.confirmReg.TextMarginTop = 0;
            this.confirmReg.TextPlaceholder = "Password";
            this.bunifuToolTip1.SetToolTip(this.confirmReg, "");
            this.bunifuToolTip1.SetToolTipIcon(this.confirmReg, null);
            this.bunifuToolTip1.SetToolTipTitle(this.confirmReg, "");
            this.confirmReg.UseSystemPasswordChar = false;
            this.confirmReg.WordWrap = true;
            this.confirmReg.TextChanged += new System.EventHandler(this.confirmReg_TextChanged);
            // 
            // passwordReg
            // 
            this.passwordReg.AcceptsReturn = false;
            this.passwordReg.AcceptsTab = false;
            this.passwordReg.AnimationSpeed = 200;
            this.passwordReg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordReg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordReg.BackColor = System.Drawing.Color.Transparent;
            this.passwordReg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordReg.BackgroundImage")));
            this.passwordReg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.passwordReg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.passwordReg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.passwordReg.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.passwordReg.BorderRadius = 1;
            this.passwordReg.BorderThickness = 3;
            this.passwordReg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordReg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordReg.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.passwordReg.DefaultText = "";
            this.passwordReg.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.passwordReg.ForeColor = System.Drawing.Color.White;
            this.passwordReg.HideSelection = true;
            this.passwordReg.IconLeft = null;
            this.passwordReg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordReg.IconPadding = 10;
            this.passwordReg.IconRight = null;
            this.passwordReg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordReg.Lines = new string[0];
            this.passwordReg.Location = new System.Drawing.Point(38, 254);
            this.passwordReg.MaxLength = 32767;
            this.passwordReg.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordReg.Modified = false;
            this.passwordReg.Multiline = false;
            this.passwordReg.Name = "passwordReg";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordReg.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordReg.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordReg.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordReg.OnIdleState = stateProperties8;
            this.passwordReg.PasswordChar = '*';
            this.passwordReg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordReg.PlaceholderText = "Password";
            this.passwordReg.ReadOnly = false;
            this.passwordReg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordReg.SelectedText = "";
            this.passwordReg.SelectionLength = 0;
            this.passwordReg.SelectionStart = 0;
            this.passwordReg.ShortcutsEnabled = true;
            this.passwordReg.Size = new System.Drawing.Size(287, 35);
            this.passwordReg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.passwordReg.TabIndex = 16;
            this.passwordReg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordReg.TextMarginBottom = 0;
            this.passwordReg.TextMarginLeft = 5;
            this.passwordReg.TextMarginTop = 0;
            this.passwordReg.TextPlaceholder = "Password";
            this.bunifuToolTip1.SetToolTip(this.passwordReg, "");
            this.bunifuToolTip1.SetToolTipIcon(this.passwordReg, null);
            this.bunifuToolTip1.SetToolTipTitle(this.passwordReg, "");
            this.passwordReg.UseSystemPasswordChar = false;
            this.passwordReg.WordWrap = true;
            this.passwordReg.TextChanged += new System.EventHandler(this.passwordReg_TextChanged);
            // 
            // phoneReg
            // 
            this.phoneReg.AcceptsReturn = false;
            this.phoneReg.AcceptsTab = false;
            this.phoneReg.AnimationSpeed = 200;
            this.phoneReg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phoneReg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phoneReg.BackColor = System.Drawing.Color.Transparent;
            this.phoneReg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phoneReg.BackgroundImage")));
            this.phoneReg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phoneReg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.phoneReg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phoneReg.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.phoneReg.BorderRadius = 1;
            this.phoneReg.BorderThickness = 3;
            this.phoneReg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phoneReg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneReg.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.phoneReg.DefaultText = "";
            this.phoneReg.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.phoneReg.ForeColor = System.Drawing.Color.White;
            this.phoneReg.HideSelection = true;
            this.phoneReg.IconLeft = null;
            this.phoneReg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneReg.IconPadding = 10;
            this.phoneReg.IconRight = null;
            this.phoneReg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneReg.Lines = new string[0];
            this.phoneReg.Location = new System.Drawing.Point(38, 197);
            this.phoneReg.MaxLength = 32767;
            this.phoneReg.MinimumSize = new System.Drawing.Size(1, 1);
            this.phoneReg.Modified = false;
            this.phoneReg.Multiline = false;
            this.phoneReg.Name = "phoneReg";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneReg.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phoneReg.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneReg.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneReg.OnIdleState = stateProperties12;
            this.phoneReg.PasswordChar = '\0';
            this.phoneReg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phoneReg.PlaceholderText = "Phone";
            this.phoneReg.ReadOnly = false;
            this.phoneReg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phoneReg.SelectedText = "";
            this.phoneReg.SelectionLength = 0;
            this.phoneReg.SelectionStart = 0;
            this.phoneReg.ShortcutsEnabled = true;
            this.phoneReg.Size = new System.Drawing.Size(287, 35);
            this.phoneReg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.phoneReg.TabIndex = 14;
            this.phoneReg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phoneReg.TextMarginBottom = 0;
            this.phoneReg.TextMarginLeft = 5;
            this.phoneReg.TextMarginTop = 0;
            this.phoneReg.TextPlaceholder = "Phone";
            this.bunifuToolTip1.SetToolTip(this.phoneReg, "");
            this.bunifuToolTip1.SetToolTipIcon(this.phoneReg, null);
            this.bunifuToolTip1.SetToolTipTitle(this.phoneReg, "");
            this.phoneReg.UseSystemPasswordChar = false;
            this.phoneReg.WordWrap = true;
            this.phoneReg.TextChanged += new System.EventHandler(this.phoneReg_TextChanged);
            // 
            // emailReg
            // 
            this.emailReg.AcceptsReturn = false;
            this.emailReg.AcceptsTab = false;
            this.emailReg.AnimationSpeed = 200;
            this.emailReg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailReg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailReg.BackColor = System.Drawing.Color.Transparent;
            this.emailReg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailReg.BackgroundImage")));
            this.emailReg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.emailReg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.emailReg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.emailReg.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.emailReg.BorderRadius = 1;
            this.emailReg.BorderThickness = 3;
            this.emailReg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailReg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailReg.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.emailReg.DefaultText = "";
            this.emailReg.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.emailReg.ForeColor = System.Drawing.Color.White;
            this.emailReg.HideSelection = true;
            this.emailReg.IconLeft = null;
            this.emailReg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailReg.IconPadding = 10;
            this.emailReg.IconRight = null;
            this.emailReg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailReg.Lines = new string[0];
            this.emailReg.Location = new System.Drawing.Point(38, 140);
            this.emailReg.MaxLength = 32767;
            this.emailReg.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailReg.Modified = false;
            this.emailReg.Multiline = false;
            this.emailReg.Name = "emailReg";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailReg.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailReg.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailReg.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailReg.OnIdleState = stateProperties16;
            this.emailReg.PasswordChar = '\0';
            this.emailReg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailReg.PlaceholderText = "Email";
            this.emailReg.ReadOnly = false;
            this.emailReg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailReg.SelectedText = "";
            this.emailReg.SelectionLength = 0;
            this.emailReg.SelectionStart = 0;
            this.emailReg.ShortcutsEnabled = true;
            this.emailReg.Size = new System.Drawing.Size(287, 35);
            this.emailReg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.emailReg.TabIndex = 13;
            this.emailReg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailReg.TextMarginBottom = 0;
            this.emailReg.TextMarginLeft = 5;
            this.emailReg.TextMarginTop = 0;
            this.emailReg.TextPlaceholder = "Email";
            this.bunifuToolTip1.SetToolTip(this.emailReg, "");
            this.bunifuToolTip1.SetToolTipIcon(this.emailReg, null);
            this.bunifuToolTip1.SetToolTipTitle(this.emailReg, "");
            this.emailReg.UseSystemPasswordChar = false;
            this.emailReg.WordWrap = true;
            this.emailReg.TextChanged += new System.EventHandler(this.emailReg_TextChanged);
            // 
            // nameReg
            // 
            this.nameReg.AcceptsReturn = false;
            this.nameReg.AcceptsTab = false;
            this.nameReg.AnimationSpeed = 200;
            this.nameReg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameReg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameReg.BackColor = System.Drawing.Color.Transparent;
            this.nameReg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameReg.BackgroundImage")));
            this.nameReg.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameReg.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.nameReg.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameReg.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.nameReg.BorderRadius = 1;
            this.nameReg.BorderThickness = 3;
            this.nameReg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameReg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameReg.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.nameReg.DefaultText = "";
            this.nameReg.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.nameReg.ForeColor = System.Drawing.Color.White;
            this.nameReg.HideSelection = true;
            this.nameReg.IconLeft = null;
            this.nameReg.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameReg.IconPadding = 10;
            this.nameReg.IconRight = null;
            this.nameReg.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameReg.Lines = new string[0];
            this.nameReg.Location = new System.Drawing.Point(38, 83);
            this.nameReg.MaxLength = 32767;
            this.nameReg.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameReg.Modified = false;
            this.nameReg.Multiline = false;
            this.nameReg.Name = "nameReg";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameReg.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameReg.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameReg.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameReg.OnIdleState = stateProperties20;
            this.nameReg.PasswordChar = '\0';
            this.nameReg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameReg.PlaceholderText = "Name";
            this.nameReg.ReadOnly = false;
            this.nameReg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameReg.SelectedText = "";
            this.nameReg.SelectionLength = 0;
            this.nameReg.SelectionStart = 0;
            this.nameReg.ShortcutsEnabled = true;
            this.nameReg.Size = new System.Drawing.Size(287, 35);
            this.nameReg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.nameReg.TabIndex = 12;
            this.nameReg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameReg.TextMarginBottom = 0;
            this.nameReg.TextMarginLeft = 5;
            this.nameReg.TextMarginTop = 0;
            this.nameReg.TextPlaceholder = "Name";
            this.bunifuToolTip1.SetToolTip(this.nameReg, "");
            this.bunifuToolTip1.SetToolTipIcon(this.nameReg, null);
            this.bunifuToolTip1.SetToolTipTitle(this.nameReg, "");
            this.nameReg.UseSystemPasswordChar = false;
            this.nameReg.WordWrap = true;
            this.nameReg.TextChanged += new System.EventHandler(this.nameReg_TextChanged);
            // 
            // loginTab
            // 
            this.loginTab.AllowToggling = false;
            this.loginTab.AnimationSpeed = 200;
            this.loginTab.AutoGenerateColors = false;
            this.loginTab.BackColor = System.Drawing.Color.Transparent;
            this.loginTab.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginTab.BackgroundImage")));
            this.loginTab.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginTab.ButtonText = "Login";
            this.loginTab.ButtonTextMarginLeft = 0;
            this.loginTab.ColorContrastOnClick = 45;
            this.loginTab.ColorContrastOnHover = 45;
            this.loginTab.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.loginTab.CustomizableEdges = borderEdges4;
            this.loginTab.DialogResult = System.Windows.Forms.DialogResult.None;
            this.loginTab.DisabledBorderColor = System.Drawing.Color.Empty;
            this.loginTab.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginTab.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.loginTab.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.loginTab.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.loginTab.ForeColor = System.Drawing.Color.White;
            this.loginTab.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.loginTab.IconMarginLeft = 11;
            this.loginTab.IconPadding = 10;
            this.loginTab.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.loginTab.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.IdleBorderRadius = 3;
            this.loginTab.IdleBorderThickness = 1;
            this.loginTab.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.IdleIconLeftImage = null;
            this.loginTab.IdleIconRightImage = null;
            this.loginTab.IndicateFocus = false;
            this.loginTab.Location = new System.Drawing.Point(138, 411);
            this.loginTab.Name = "loginTab";
            this.loginTab.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.onHoverState.BorderRadius = 3;
            this.loginTab.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginTab.onHoverState.BorderThickness = 1;
            this.loginTab.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginTab.onHoverState.IconLeftImage = null;
            this.loginTab.onHoverState.IconRightImage = null;
            this.loginTab.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.OnIdleState.BorderRadius = 3;
            this.loginTab.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginTab.OnIdleState.BorderThickness = 1;
            this.loginTab.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.loginTab.OnIdleState.IconLeftImage = null;
            this.loginTab.OnIdleState.IconRightImage = null;
            this.loginTab.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.OnPressedState.BorderRadius = 3;
            this.loginTab.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginTab.OnPressedState.BorderThickness = 1;
            this.loginTab.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.loginTab.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.loginTab.OnPressedState.IconLeftImage = null;
            this.loginTab.OnPressedState.IconRightImage = null;
            this.loginTab.Size = new System.Drawing.Size(73, 23);
            this.loginTab.TabIndex = 10;
            this.loginTab.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.loginTab.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.loginTab, "");
            this.bunifuToolTip1.SetToolTipIcon(this.loginTab, null);
            this.bunifuToolTip1.SetToolTipTitle(this.loginTab, "");
            this.loginTab.UseDefaultRadiusAndThickness = true;
            this.loginTab.Click += new System.EventHandler(this.loginTab_Click);
            // 
            // registerBtn
            // 
            this.registerBtn.AllowToggling = false;
            this.registerBtn.AnimationSpeed = 200;
            this.registerBtn.AutoGenerateColors = false;
            this.registerBtn.BackColor = System.Drawing.Color.Transparent;
            this.registerBtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.registerBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("registerBtn.BackgroundImage")));
            this.registerBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registerBtn.ButtonText = "Register";
            this.registerBtn.ButtonTextMarginLeft = 0;
            this.registerBtn.ColorContrastOnClick = 45;
            this.registerBtn.ColorContrastOnHover = 45;
            this.registerBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.registerBtn.CustomizableEdges = borderEdges5;
            this.registerBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.registerBtn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.registerBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.registerBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.registerBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.registerBtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.registerBtn.ForeColor = System.Drawing.Color.White;
            this.registerBtn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.registerBtn.IconMarginLeft = 11;
            this.registerBtn.IconPadding = 10;
            this.registerBtn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.registerBtn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.registerBtn.IdleBorderRadius = 30;
            this.registerBtn.IdleBorderThickness = 1;
            this.registerBtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.registerBtn.IdleIconLeftImage = null;
            this.registerBtn.IdleIconRightImage = null;
            this.registerBtn.IndicateFocus = false;
            this.registerBtn.Location = new System.Drawing.Point(78, 364);
            this.registerBtn.Name = "registerBtn";
            this.registerBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.registerBtn.onHoverState.BorderRadius = 30;
            this.registerBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registerBtn.onHoverState.BorderThickness = 1;
            this.registerBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.registerBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.registerBtn.onHoverState.IconLeftImage = null;
            this.registerBtn.onHoverState.IconRightImage = null;
            this.registerBtn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.registerBtn.OnIdleState.BorderRadius = 30;
            this.registerBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registerBtn.OnIdleState.BorderThickness = 1;
            this.registerBtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(33)))), ((int)(((byte)(86)))));
            this.registerBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.registerBtn.OnIdleState.IconLeftImage = null;
            this.registerBtn.OnIdleState.IconRightImage = null;
            this.registerBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registerBtn.OnPressedState.BorderRadius = 30;
            this.registerBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.registerBtn.OnPressedState.BorderThickness = 1;
            this.registerBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.registerBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.registerBtn.OnPressedState.IconLeftImage = null;
            this.registerBtn.OnPressedState.IconRightImage = null;
            this.registerBtn.Size = new System.Drawing.Size(198, 38);
            this.registerBtn.TabIndex = 9;
            this.registerBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.registerBtn.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.registerBtn, "");
            this.bunifuToolTip1.SetToolTipIcon(this.registerBtn, null);
            this.bunifuToolTip1.SetToolTipTitle(this.registerBtn, "");
            this.registerBtn.UseDefaultRadiusAndThickness = true;
            this.registerBtn.Click += new System.EventHandler(this.registerBtn_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 21.75F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(104, 24);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(177, 42);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "WAREHOUSE";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuPictureBox4
            // 
            this.bunifuPictureBox4.AllowFocused = false;
            this.bunifuPictureBox4.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox4.BorderRadius = 0;
            this.bunifuPictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox4.Image")));
            this.bunifuPictureBox4.IsCircle = false;
            this.bunifuPictureBox4.Location = new System.Drawing.Point(8, -6);
            this.bunifuPictureBox4.Name = "bunifuPictureBox4";
            this.bunifuPictureBox4.Size = new System.Drawing.Size(79, 79);
            this.bunifuPictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox4.TabIndex = 1;
            this.bunifuPictureBox4.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox4, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox4, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox4, "");
            this.bunifuPictureBox4.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // LoginForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.ClientSize = new System.Drawing.Size(371, 502);
            this.Controls.Add(this.bunifuPages1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "LoginForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "LoginForm";
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ExitBtn)).EndInit();
            this.bunifuPages1.ResumeLayout(false);
            this.Login.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuImageButton1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.Register.ResumeLayout(false);
            this.Register.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorConfirm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorPassword)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorPhone)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorEmail)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox4)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage Login;
        private Bunifu.Framework.UI.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton signInTab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton loginBtn;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.TabPage Register;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton loginTab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton registerBtn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox4;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.Framework.UI.BunifuImageButton ExitBtn;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox nameReg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox confirmReg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox phoneReg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox emailReg;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox3;
        private Bunifu.Framework.UI.BunifuMaterialTextbox passwordLogin;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.Framework.UI.BunifuMaterialTextbox emailLogin;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private Bunifu.UI.WinForms.BunifuPictureBox errorConfirm;
        private Bunifu.UI.WinForms.BunifuPictureBox errorPassword;
        private Bunifu.UI.WinForms.BunifuPictureBox errorPhone;
        private Bunifu.UI.WinForms.BunifuPictureBox errorEmail;
        private Bunifu.UI.WinForms.BunifuPictureBox errorName;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox passwordReg;
    }
}